// Shared mock data for CX Pro prototype
window.CXP_DATA = (() => {
  const projects = [
    {
      id: "p-aurora",
      number: "24-118",
      name: "Aurora Medical Center — Phase II",
      client: "Aurora Health System",
      location: "Denver, CO",
      type: "Healthcare · 412,000 SF",
      phase: "Functional Testing",
      progress: 0.62,
      equipment: 487,
      issues: { open: 34, critical: 4, total: 612 },
      checklists: { complete: 1284, total: 2106 },
      tests: { complete: 89, total: 312 },
      milestone: "Substantial Completion · Jun 14",
      lead: "M. Okafor",
      img: "aurora",
    },
    {
      id: "p-meridian",
      number: "24-094",
      name: "Meridian Data Center MC-04",
      client: "Meridian Cloud",
      location: "Hillsboro, OR",
      type: "Data Center · 88 MW",
      phase: "Pre-Functional",
      progress: 0.34,
      equipment: 1842,
      issues: { open: 71, critical: 12, total: 814 },
      checklists: { complete: 1942, total: 5604 },
      tests: { complete: 18, total: 488 },
      milestone: "Whitespace Energization · Aug 02",
      lead: "K. Roselli",
      img: "meridian",
    },
    {
      id: "p-northpoint",
      number: "23-061",
      name: "Northpoint Tower",
      client: "Halcyon Properties",
      location: "Seattle, WA",
      type: "Office · 38 floors",
      phase: "Closeout",
      progress: 0.94,
      equipment: 312,
      issues: { open: 6, critical: 0, total: 421 },
      checklists: { complete: 1198, total: 1204 },
      tests: { complete: 246, total: 256 },
      milestone: "Final Report · May 30",
      lead: "S. Patel",
      img: "northpoint",
    },
    {
      id: "p-foundry",
      number: "25-007",
      name: "Foundry Labs Cleanroom Expansion",
      client: "Foundry Semiconductor",
      location: "Chandler, AZ",
      type: "Industrial · Class 100",
      phase: "Design Review",
      progress: 0.08,
      equipment: 96,
      issues: { open: 2, critical: 0, total: 14 },
      checklists: { complete: 0, total: 312 },
      tests: { complete: 0, total: 84 },
      milestone: "Issue for Construction · Jul 18",
      lead: "M. Okafor",
      img: "foundry",
    },
  ];

  const equipment = [
    { id: "AHU-01", type: "Air Handling Unit", system: "HVAC", building: "A", floor: "Roof", area: "East Penthouse", status: "Operational", install: 1.0, startup: 1.0, pfc: 1.0, fpt: 1.0, issues: 0, mfg: "Trane", model: "T-CLIMATE-CG-040" },
    { id: "AHU-02", type: "Air Handling Unit", system: "HVAC", building: "A", floor: "Roof", area: "West Penthouse", status: "Operational", install: 1.0, startup: 1.0, pfc: 1.0, fpt: 0.66, issues: 2, mfg: "Trane", model: "T-CLIMATE-CG-040" },
    { id: "AHU-03", type: "Air Handling Unit", system: "HVAC", building: "A", floor: "Roof", area: "Central Penthouse", status: "Functional Testing", install: 1.0, startup: 1.0, pfc: 0.82, fpt: 0.41, issues: 5, mfg: "Trane", model: "T-CLIMATE-CG-060", hero: true },
    { id: "AHU-04", type: "Air Handling Unit", system: "HVAC", building: "B", floor: "Roof", area: "Surgical Tower", status: "Startup", install: 1.0, startup: 0.5, pfc: 0.0, fpt: 0.0, issues: 1, mfg: "Trane", model: "T-CLIMATE-CG-060" },
    { id: "CH-01", type: "Chiller", system: "HVAC", building: "Central Plant", floor: "L1", area: "Mech Yard", status: "Operational", install: 1.0, startup: 1.0, pfc: 1.0, fpt: 0.91, issues: 1, mfg: "York", model: "YMC2-S0700" },
    { id: "CH-02", type: "Chiller", system: "HVAC", building: "Central Plant", floor: "L1", area: "Mech Yard", status: "Pre-Functional", install: 1.0, startup: 1.0, pfc: 0.44, fpt: 0.0, issues: 3, mfg: "York", model: "YMC2-S0700" },
    { id: "B-01", type: "Boiler", system: "HVAC", building: "Central Plant", floor: "L1", area: "Boiler Room", status: "Operational", install: 1.0, startup: 1.0, pfc: 1.0, fpt: 1.0, issues: 0, mfg: "Cleaver-Brooks", model: "CFC-E-800" },
    { id: "P-CHW-01", type: "Pump", system: "HVAC", building: "Central Plant", floor: "L1", area: "Mech Yard", status: "Operational", install: 1.0, startup: 1.0, pfc: 1.0, fpt: 0.66, issues: 1, mfg: "Bell & Gossett", model: "e-1510-5GB" },
    { id: "P-CHW-02", type: "Pump", system: "HVAC", building: "Central Plant", floor: "L1", area: "Mech Yard", status: "Operational", install: 1.0, startup: 1.0, pfc: 1.0, fpt: 0.66, issues: 0, mfg: "Bell & Gossett", model: "e-1510-5GB" },
    { id: "VAV-3-118", type: "VAV Box", system: "HVAC", building: "A", floor: "L3", area: "Patient Room 318", status: "Pre-Functional", install: 1.0, startup: 1.0, pfc: 0.0, fpt: 0.0, issues: 0, mfg: "Titus", model: "DESV-3000" },
    { id: "VAV-3-119", type: "VAV Box", system: "HVAC", building: "A", floor: "L3", area: "Patient Room 319", status: "Pre-Functional", install: 1.0, startup: 1.0, pfc: 0.0, fpt: 0.0, issues: 0, mfg: "Titus", model: "DESV-3000" },
    { id: "VAV-3-120", type: "VAV Box", system: "HVAC", building: "A", floor: "L3", area: "Patient Room 320", status: "Installed", install: 1.0, startup: 0.0, pfc: 0.0, fpt: 0.0, issues: 1, mfg: "Titus", model: "DESV-3000" },
    { id: "ATS-01", type: "Automatic Transfer Switch", system: "Electrical", building: "Central Plant", floor: "L1", area: "Main Electrical", status: "Operational", install: 1.0, startup: 1.0, pfc: 1.0, fpt: 0.88, issues: 0, mfg: "ASCO", model: "7000-4000A" },
    { id: "GEN-01", type: "Generator", system: "Electrical", building: "Central Plant", floor: "L1", area: "Gen Yard", status: "Functional Testing", install: 1.0, startup: 1.0, pfc: 1.0, fpt: 0.5, issues: 2, mfg: "Caterpillar", model: "C32-2000ekW" },
    { id: "FA-FACP-01", type: "Fire Alarm Panel", system: "Life Safety", building: "A", floor: "L1", area: "FCC", status: "Functional Testing", install: 1.0, startup: 1.0, pfc: 1.0, fpt: 0.72, issues: 1, mfg: "Notifier", model: "NFS2-3030" },
  ];

  // Hero checklist: AHU-03 Pre-Functional
  const checklist = {
    id: "PFC-AHU-03",
    number: "PFC-0314",
    title: "Pre-Functional Checklist — Air Handling Unit",
    asset: "AHU-03",
    template: "AHU Pre-Functional v3.2",
    assignedTo: "Westgate Mechanical · J. Reyes",
    cxAuthority: "M. Okafor · CxA",
    discipline: "Mechanical",
    status: "In Progress",
    started: "May 12, 2026",
    progress: 0.62,
    sections: [
      {
        id: "general",
        title: "General Installation",
        lines: [
          { n: "1.01", q: "Equipment matches submittal data (manufacturer, model, serial)", type: "ynna", answer: "yes", responder: "J. Reyes", date: "05·12·26" },
          { n: "1.02", q: "Equipment installed per manufacturer's recommendations", type: "ynna", answer: "yes", responder: "J. Reyes", date: "05·12·26" },
          { n: "1.03", q: "Equipment installed per contract documents (drawings, specs)", type: "ynna", answer: "yes", responder: "J. Reyes", date: "05·12·26" },
          { n: "1.04", q: "Vibration isolators installed and properly adjusted", type: "ynna", answer: "no", responder: "J. Reyes", date: "05·12·26", issues: 1, note: "Spring isolators on supply fan show full compression — see Issue #4421" },
          { n: "1.05", q: "Equipment is labeled per project standard", type: "ynna", answer: "yes", responder: "J. Reyes", date: "05·12·26" },
          { n: "1.06", q: "Access for service and maintenance is adequate", type: "ynna", answer: "yes", responder: "J. Reyes", date: "05·12·26", files: 2 },
        ],
      },
      {
        id: "mechanical",
        title: "Mechanical · Ductwork & Coils",
        lines: [
          { n: "2.01", q: "Supply, return, and outside air dampers operate freely and seal", type: "ynna", answer: "yes", responder: "J. Reyes", date: "05·13·26" },
          { n: "2.02", q: "Filters installed, sized per spec, and clean", type: "ynna", answer: "yes", responder: "J. Reyes", date: "05·13·26" },
          { n: "2.03", q: "Cooling coil installed, piped, and free of debris", type: "ynna", answer: "yes", responder: "J. Reyes", date: "05·13·26" },
          { n: "2.04", q: "Heating coil installed, piped, and free of debris", type: "ynna", answer: "yes", responder: "J. Reyes", date: "05·13·26" },
          { n: "2.05", q: "Condensate trap installed at correct depth and primed", type: "ynna", answer: null, ai: true },
          { n: "2.06", q: "Static pressure (in. w.c.) at design airflow", type: "numeric", units: "in. w.c.", value: "1.85", target: "1.75 ± 0.25", answer: "yes", responder: "J. Reyes", date: "05·14·26" },
          { n: "2.07", q: "Differential pressure across filter rack", type: "numeric", units: "in. w.c.", value: "0.42", target: "≤ 0.50", answer: "yes", responder: "J. Reyes", date: "05·14·26" },
          { n: "2.08", q: "Drain pan slopes to drain and is leak-free", type: "ynna", answer: "no", responder: "J. Reyes", date: "05·14·26", issues: 1, note: "Standing water 1/4\" at NE corner — see Issue #4438" },
        ],
      },
      {
        id: "electrical",
        title: "Electrical · Power & Disconnects",
        lines: [
          { n: "3.01", q: "Disconnect within sight, properly sized, and labeled", type: "ynna", answer: "yes", responder: "T. Wilkes", date: "05·14·26" },
          { n: "3.02", q: "Voltage and phase verified at unit (V, A, Hz)", type: "numeric", units: "V / Hz", value: "478.4 / 60.0", target: "480 ± 10 / 60", answer: "yes", responder: "T. Wilkes", date: "05·14·26" },
          { n: "3.03", q: "VFD installed, programmed per sequence of operations", type: "ynna", answer: null },
          { n: "3.04", q: "Motor amperage at full load (A)", type: "numeric", units: "A", value: null, target: "≤ 42.0" },
          { n: "3.05", q: "Equipment grounded per NEC and contract documents", type: "ynna", answer: null },
        ],
      },
      {
        id: "controls",
        title: "Controls · BAS Integration",
        lines: [
          { n: "4.01", q: "All control points wired and tagged per points list", type: "ynna", answer: null },
          { n: "4.02", q: "Sensors (SAT, RAT, MAT, OAT) calibrated within tolerance", type: "ynna", answer: null },
          { n: "4.03", q: "Damper actuators stroke fully and modulate smoothly", type: "ynna", answer: null },
          { n: "4.04", q: "BACnet device visible on network with correct address", type: "ynna", answer: null },
          { n: "4.05", q: "Graphics published to BAS front end", type: "ynna", answer: null },
        ],
      },
    ],
  };

  const issues = [
    { id: "4421", title: "AHU-03 supply fan vibration isolators fully compressed", asset: "AHU-03", priority: "High", status: "Open", assigned: "Westgate Mechanical", age: 2 },
    { id: "4438", title: "AHU-03 condensate drain pan holds 1/4\" standing water", asset: "AHU-03", priority: "Medium", status: "Open", assigned: "Westgate Mechanical", age: 1 },
    { id: "4402", title: "GEN-01 day tank low-level alarm wiring open", asset: "GEN-01", priority: "Critical", status: "In Progress", assigned: "Halverson Electric", age: 4 },
    { id: "4388", title: "CH-02 chilled water flow switch installed reversed", asset: "CH-02", priority: "High", status: "Open", assigned: "Westgate Mechanical", age: 6 },
  ];

  const activity = [
    { who: "M. Okafor", what: "closed", target: "Issue #4380", when: "2m" },
    { who: "AI Agent", what: "generated 124 checklist lines from", target: "AHU-Submittal-Rev3.pdf", when: "8m", ai: true },
    { who: "J. Reyes", what: "completed PFC line 2.07 on", target: "AHU-03", when: "14m" },
    { who: "T. Wilkes", what: "opened", target: "Issue #4441", when: "22m" },
    { who: "AI Agent", what: "matched 38 nameplate photos to equipment in", target: "VAV-Field-Survey.zip", when: "1h", ai: true },
    { who: "S. Patel", what: "approved Functional Test", target: "FT-CH-01-S04", when: "1h" },
    { who: "K. Roselli", what: "uploaded", target: "Drawing M-301 Rev D", when: "2h" },
  ];

  return { projects, equipment, checklist, issues, activity };
})();
